#!/bin/sh

ID3EDIT="id3edit"
ARG="$1"

if [ "$ARG" = "--help" -o "$ARG" = "-h" ]; then
    $ID3EDIT --help
    exit 0
fi

if [ "$ARG" = "--version" -o "$ARG" = "-v" ]; then
    $ID3EDIT --version
    exit 0
fi

$ID3EDIT --readonly --get-framelist "$ARG"

# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

